# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Church at the Old Manse
email: enquires@churchattheoldmanse.co.uk
description: > # this means to ignore newlines until "baseurl:"
  The Church at The Old Manse provides a unique, large, luxury, self catering property
   for exploring central Scotland. With five bedrooms; stunning open plan kitchen and lounge;
   galleried snooker area; and sauna and steam room, The Church at the Old Manse is a fantastic 
   base giving easy access to Glasgow, Edinburgh, Livingston and Lanark.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
